services:
  cockroachdb:
    image: cockroachdb/cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./data/cockroachdb:/cockroach/cockroach-data
    command: start-single-node --insecure
